### ISSUE TITLE
Unable to Generate SSH Certificate

### ISSUE THREAD

**Issue by vorasmit** [frappe/press#1010]
## Traceback

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 56, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 53, in handle
    return _RESTAPIHandler(call, doctype, name).get_response()
  File "apps/frappe/frappe/api.py", line 69, in get_response
    return self.handle_method()
  File "apps/frappe/frappe/api.py", line 79, in handle_method
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1586, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "apps/press/press/api/site.py", line 56, in wrapper
    return wrapped(*args, **kwargs)
  File "apps/press/press/api/bench.py", line 806, in generate_certificate
    ).insert()
  File "apps/frappe/frappe/model/document.py", line 286, in insert
    self.run_method("after_insert")
  File "apps/frappe/frappe/model/document.py", line 926, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1280, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1262, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 923, in fn
    return method_object(*args, **kwargs)
  File "apps/press/press/press/doctype/ssh_certificate/ssh_certificate.py", line 66, in after_insert
    self.generate_certificate()
  File "apps/press/press/press/doctype/ssh_certificate/ssh_certificate.py", line 73, in generate_certificate
    ca.sign(
  File "apps/press/press/press/doctype/ssh_certificate_authority/ssh_certificate_authority.py", line 59, in sign
    self.run(
  File "apps/press/press/press/doctype/ssh_certificate_authority/ssh_certificate_authority.py", line 28, in run
    return subprocess.check_output(
  File "/home/frappe/.pyenv/versions/3.10.0/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/frappe/.pyenv/versions/3.10.0/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ssh-keygen', '-s', 'ca', '-t', 'rsa-sha2-512', '-I', '********', '-n', 'bench-3942', '-z', '00004411', '-O', 'no-port-forwarding', '-O', 'no-user-rc', '-O', 'no-x11-forwarding', '-O', 'no-agent-forwarding', '-O', 'permit-pty', '-V', '+6h', '/tmp/id_rsa-00004411.pub']' died with <Signals.SIGPIPE: 13>.
```

**Comment by saurabh6790** [comment]
@vorasmit Are you still facing this issue? If so, please share steps!

**Comment by vorasmit** [comment]
On click of Generate SSH Certificate, this issue occurs.

![image](https://github.com/frappe/press/assets/10496564/452b031a-5a07-455c-9203-b5117e8550b7)

**Comment by vorasmit** [comment]
Was able to generate SSH now. Is it resolved or the issue is something else?

**Comment by saurabh6790** [comment]
@vorasmit We have fixed the ssh certificate generation process.  Closing this issue

**Comment by mohsinalimat** [comment]
Facing same issue

https://github.com/frappe/press/issues/1655
