### ISSUE TITLE
Error: Data missing in table: Apps

### ISSUE THREAD

**Issue by vineyrawat** [frappe/press#1134]
Hi,

I'm trying to create a deployment candidate form the release group event though I've added all necessary details like app details in apps child table and server details in server child table but it is still throwing the below error:

`Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/handler.py", line 309, in run_doc_method
    response = doc.run_method(method, args)
  File "apps/frappe/frappe/model/document.py", line 917, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1279, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1261, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 914, in fn
    return method_object(*args, **kwargs)
  File "apps/press/press/press/doctype/release_group/release_group.py", line 245, in create_deploy_candidate
    ).insert()
  File "apps/frappe/frappe/model/document.py", line 262, in insert
    self._validate()
  File "apps/frappe/frappe/model/document.py", line 531, in _validate
    self._validate_mandatory()
  File "apps/frappe/frappe/model/document.py", line 866, in _validate_mandatory
    raise frappe.MandatoryError(
frappe.exceptions.MandatoryError: [Deploy Candidate, deploy-0001-000001]: apps`

![image](https://github.com/frappe/press/assets/77631301/045af932-3330-476c-bdb1-318edc5210a0)

Is there something that I'm missing?

**Comment by vineyrawat** [comment]
Hi, the above issue have been fixed, the issue was of the branch, I've put the main branch instead of version-14 in app creation due to which the github sync poll is failed
