### ISSUE TITLE
Slow Queries Report on Dashboard is broken

### ISSUE THREAD

**Issue by shadrak98** [frappe/press#1173]
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 108, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 53, in handle
    return _RESTAPIHandler(call, doctype, name).get_response()
  File "apps/frappe/frappe/api.py", line 69, in get_response
    return self.handle_method()
  File "apps/frappe/frappe/api.py", line 79, in handle_method
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/press/press/api/site.py", line 50, in wrapper
    return wrapped(*args, **kwargs)
  File "apps/press/press/api/analytics.py", line 546, in mariadb_slow_queries
    rows = get_slow_query_logs(
  File "apps/press/press/press/report/mariadb_slow_queries/mariadb_slow_queries.py", line 116, in get_slow_query_logs
    for d in response["hits"]["hits"]:
KeyError: 'hits'
```

**Comment by ankush** [comment]
https://github.com/frappe/press/commit/8d3044855ee21bd9fc842bec3bcf3688d7b96089
