### ISSUE TITLE
Show proper error message

### ISSUE THREAD

**Issue by michellealva** [frappe/press#1357]
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1704, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/press/press/api/billing.py", line 382, in change_payment_mode
    team.save()
  File "apps/frappe/frappe/model/document.py", line 334, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 386, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1120, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 952, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1318, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1300, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 949, in fn
    return method_object(*args, **kwargs)
  File "apps/press/press/press/doctype/team/team.py", line 311, in on_update
    self.validate_payment_mode()
  File "apps/press/press/press/doctype/team/team.py", line 294, in validate_payment_mode
    frappe.throw("No card added")
  File "apps/frappe/frappe/__init__.py", line 592, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 564, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 515, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: No card added
```

![IMAGE 2024-01-15 16:59:24](https://github.com/frappe/press/assets/50285544/512a6ec0-2921-4c2d-b240-f17bb6655b57)

**Comment by ankush** [comment]
Fix it permanently, instead of one at a time:

https://github.com/frappe/frappe-ui/commit/578647ba33f7f93f4087d7ab12a180d647391841 
https://github.com/frappe/helpdesk/commit/318a7dbc5e3dcb2e32aa3b266cb2ae681eaaeddd

**Comment by BreadGenie** [comment]
fixed in https://github.com/frappe/press/commit/c174c840fb064a1e7b6d130559f815a1a17116b0
