### ISSUE TITLE
Site migrate doesn't work

### ISSUE THREAD

**Issue by michellealva** [frappe/press#1364]
<img width="1680" alt="image" src="https://github.com/frappe/press/assets/50285544/b52d1244-6d03-4107-bdbb-11df5fae24c4">

```
runtime-core.esm-bundler.js:226 TypeError: w(...).options.onRowClick is not a function
    at onClick (ListRow.vue:71:2)
    at hr (runtime-core.esm-bundler.js:158:18)
    at on (runtime-core.esm-bundler.js:166:17)
    at HTMLDivElement.n (runtime-dom.esm-bundler.js:278:5)
m2 @ runtime-core.esm-bundler.js:226
focus-trap.js:1 There are no focusable elements inside the <FocusTrap />
(anonymous) @ focus-trap.js:1
/api/method/press.api.client.run_doc_method:1 
        
        
       Failed to load resource: the server responded with a status of 500 ()
frappeRequest.js:67 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1704, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/press/press/api/client.py", line 132, in run_doc_method
    _run_doc_method(dt=dt, dn=dn, method=method, args=args)
  File "apps/frappe/frappe/handler.py", line 333, in run_doc_method
    response = doc.run_method(method, **args)
  File "apps/frappe/frappe/model/document.py", line 952, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1318, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1300, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 949, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
TypeError: Site.migrate() got an unexpected keyword argument 'skip_failing'

frappeRequest.js:71 Uncaught (in promise) Error: /api/method/press.api.client.run_doc_method TypeError
    at frappeRequest.js:71:17
    at Generator.next (<anonymous>)
    at s (common_site_config-d4a7b87a.js:1:668)
```

**Comment by BreadGenie** [comment]
fixed by e92b42e
