### ISSUE TITLE
TypeError: 'str' object does not support item assignment

### ISSUE THREAD

**Issue by HUMENTH** [frappe/press#1385]
1. Mandatory field "Title" under "Apps"(child table) is hidden.
2. Getting error on creating "Release Group".

`### App Versions
```
{
	"frappe": "15.10.0",
	"press": "0.7.0"
}
```
### Route
```
Form/Release Group/new-release-group-xcqbgdqiss
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 18, in savedocs
    doc = frappe.get_doc(json.loads(doc))
  File "apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 82, in get_doc
    return controller(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 132, in __init__
    super().__init__(kwargs)
  File "apps/frappe/frappe/model/base_document.py", line 133, in __init__
    self.update(d)
  File "apps/frappe/frappe/model/base_document.py", line 182, in update
    self.set(key, value, as_value=ignore_children)
  File "apps/frappe/frappe/model/base_document.py", line 234, in set
    self.extend(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 275, in extend
    self.append(key, v)
  File "apps/frappe/frappe/model/base_document.py", line 260, in append
    ret_value = self._init_child(value, key)
  File "apps/frappe/frappe/model/base_document.py", line 288, in _init_child
    value["doctype"] = doctype
TypeError: 'str' object does not support item assignment

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Release Group\",\"name\":\"new-release-group-xcqbgdqiss\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"enabled\":1,\"default\":0,\"public\":0,\"central_bench\":0,\"servers\":[{\"docstatus\":0,\"doctype\":\"Release Group Server\",\"name\":\"new-release-group-server-knukqqytul\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"default\":0,\"parent\":\"new-release-group-xcqbgdqiss\",\"parentfield\":\"servers\",\"parenttype\":\"Release Group\",\"idx\":1,\"__unedited\":false,\"server\":\"f1.remoread.com\"}],\"apps\":[{\"docstatus\":0,\"doctype\":\"Release Group App\",\"name\":\"new-release-group-app-dhnzujdcze\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"enable_auto_deploy\":1,\"parent\":\"new-release-group-xcqbgdqiss\",\"parentfield\":\"apps\",\"parenttype\":\"Release Group\",\"idx\":1,\"__unedited\":false,\"title\":\"Frappe\",\"app\":\"frappe\",\"source\":\"SRC-frappe-001\"}],\"common_site_config_table\":\"{}\",\"common_site_config\":\"{}\",\"bench_config\":\"{}\",\"gunicorn_threads_per_worker\":0,\"dependencies\":[],\"packages\":[],\"environment_variables\":[],\"mounts\":[],\"is_redisearch_enabled\":0,\"is_push_to_deploy_enabled\":0,\"is_delta_build_enabled\":0,\"merge_all_rq_queues\":0,\"merge_default_and_short_rq_queues\":0,\"use_rq_workerpool\":0,\"saas_bench\":0,\"tags\":[],\"is_code_server_enabled\":0,\"team\":\"620659bad4\",\"title\":\"Test Release Group\",\"version\":\"Nightly\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery370089470862383873161": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 990,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "TypeError: 'str' object does not support item assignment",
	"exc_type": "TypeError"
}
````

**Comment by recorner** [comment]
did you get a solution to your error?
