### ISSUE TITLE
Create App Release un-available features

### ISSUE THREAD

**Issue by recorner** [frappe/press#1427]
am trying to  create an app release and i am getting 
### App Versions
```
{
	"builder": "1.4.0",
	"erpnext": "15.12.2",
	"frappe": "15.13.0",
	"helpdesk": "0.10.0",
	"hrms": "15.11.0",
	"press": "0.7.0"
}
```
### Route
```
Form/Release Group/new-release-group-vezzawzdgh
```
### Traceback

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 18, in savedocs
    doc = frappe.get_doc(json.loads(doc))
  File "apps/frappe/frappe/__init__.py", line 1271, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 82, in get_doc
    return controller(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 132, in __init__
    super().__init__(kwargs)
  File "apps/frappe/frappe/model/base_document.py", line 134, in __init__
    self.update(d)
  File "apps/frappe/frappe/model/base_document.py", line 184, in update
    self.set(key, value, as_value=ignore_children)
  File "apps/frappe/frappe/model/base_document.py", line 236, in set
    self.extend(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 294, in extend
    self.append(key, v)
  File "apps/frappe/frappe/model/base_document.py", line 262, in append
    ret_value = self._init_child(value, key)
  File "apps/frappe/frappe/model/base_document.py", line 307, in _init_child
    value["doctype"] = doctype
TypeError: 'str' object does not support item assignment

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Release Group\",\"name\":\"new-release-group-vezzawzdgh\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"enabled\":1,\"default\":1,\"public\":1,\"central_bench\":1,\"servers\":[{\"docstatus\":0,\"doctype\":\"Release Group Server\",\"name\":\"new-release-group-server-ytyydljluo\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"default\":0,\"parent\":\"new-release-group-vezzawzdgh\",\"parentfield\":\"servers\",\"parenttype\":\"Release Group\",\"idx\":1,\"__unedited\":false,\"server\":\"f1.optimoerp.co.ke\"}],\"apps\":[{\"docstatus\":0,\"doctype\":\"Release Group App\",\"name\":\"new-release-group-app-mfocwxmdps\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"enable_auto_deploy\":0,\"parent\":\"new-release-group-vezzawzdgh\",\"parentfield\":\"apps\",\"parenttype\":\"Release Group\",\"idx\":1,\"__unedited\":false,\"title\":\"Frappe\",\"app\":\"frappe\",\"source\":\"SRC-frappe-001\"}],\"common_site_config_table\":\"{}\",\"common_site_config\":\"{}\",\"bench_config\":\"{}\",\"gunicorn_threads_per_worker\":0,\"dependencies\":[],\"packages\":[],\"environment_variables\":[],\"mounts\":[],\"is_redisearch_enabled\":0,\"is_push_to_deploy_enabled\":0,\"is_delta_build_enabled\":0,\"merge_all_rq_queues\":0,\"merge_default_and_short_rq_queues\":0,\"use_rq_workerpool\":0,\"saas_bench\":0,\"tags\":[],\"is_code_server_enabled\":1,\"team\":\"ee35f8d13d\",\"title\":\"Frappe Nigtly\",\"version\":\"Nightly\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery370041901342514360351": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 1067,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "TypeError: 'str' object does not support item assignment",
	"exc_type": "TypeError"
}
```
also  here are the missing featue flags 
![image](https://github.com/frappe/press/assets/89336832/9b938d93-a580-4bfc-9d28-74b5be57b77c)
cant add or edit dependancies 
2)features missing in the feature flag 
![image](https://github.com/frappe/press/assets/89336832/9b1865b4-7dba-4fcc-8507-615373ced28a)
3)also the saas config tab not populating with the items 
![image](https://github.com/frappe/press/assets/89336832/0f0431e8-8324-4850-80bc-621f8a5cd49d)

**Comment by recorner** [comment]
@rmehta  what could be the problem?
