### ISSUE TITLE
not able Generate SSH Certificate

### ISSUE THREAD

**Issue by mohsinalimat** [frappe/press#1655]
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1795, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/press/press/api/client.py", line 224, in run_doc_method
    _run_doc_method(dt=dt, dn=dn, method=method, args=args)
  File "apps/frappe/frappe/handler.py", line 326, in run_doc_method
    response = doc.run_method(method)
  File "apps/frappe/frappe/model/document.py", line 964, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1324, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1306, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 961, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/press/press/press/doctype/release_group/release_group.py", line 750, in generate_certificate
    ).insert()
  File "apps/frappe/frappe/model/document.py", line 307, in insert
    self.run_method("after_insert")
  File "apps/frappe/frappe/model/document.py", line 964, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1324, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1306, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 961, in fn
    return method_object(*args, **kwargs)
  File "apps/press/press/press/doctype/ssh_certificate/ssh_certificate.py", line 94, in after_insert
    self.generate_certificate()
  File "apps/press/press/press/doctype/ssh_certificate/ssh_certificate.py", line 101, in generate_certificate
    ca.sign(
  File "apps/press/press/press/doctype/ssh_certificate_authority/ssh_certificate_authority.py", line 80, in sign
    self.run(
  File "apps/press/press/press/doctype/ssh_certificate_authority/ssh_certificate_authority.py", line 45, in run
    return subprocess.check_output(
  File "/home/frappe/.pyenv/versions/3.10.0/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/frappe/.pyenv/versions/3.10.0/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ssh-keygen', '-s', 'ca', '-t', 'rsa-sha2-512', '-I', 'business@matiyas.com', '-n', 'bench-10239', '-z', '00007990', '-O', 'no-port-forwarding', '-O', 'no-user-rc', '-O', 'no-x11-forwarding', '-O', 'no-agent-forwarding', '-O', 'permit-pty', '-V', '+6h', '/tmp/id_rsa-00007990.pub']' returned non-zero exit status 255.

**Comment by balamurali27** [comment]
Issue was due to bad public key. Only substring was pasted. Validation needs to be better. Maybe we can get length from prefix and verify the entirely of the same.
