### ISSUE TITLE
Permission error when creating a new tag in frappecloud new dashboard

### ISSUE THREAD

**Issue by IMS94** [frappe/press#1812]
$subject

I get the following error in console when trying to create and assign a tag to a site in FrappeCloud. I'm logged in with the admin user (owner account).

```python
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1795, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/press/press/api/client.py", line 259, in run_doc_method
    _run_doc_method(dt=dt, dn=dn, method=method, args=args)
  File "apps/frappe/frappe/handler.py", line 332, in run_doc_method
    response = doc.run_method(method, **args)
  File "apps/frappe/frappe/model/document.py", line 964, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1324, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1306, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 961, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/press/press/press/doctype/resource_tag/tag_helpers.py", line 22, in add_resource_tag
    ).insert()
  File "apps/frappe/frappe/model/document.py", line 282, in insert
    self.check_permission("create")
  File "apps/frappe/frappe/model/document.py", line 218, in check_permission
    self.raise_no_permission_to(permtype)
  File "apps/frappe/frappe/model/document.py", line 239, in raise_no_permission_to
    raise frappe.PermissionError
frappe.exceptions.PermissionError
```

**Comment by BreadGenie** [comment]
https://github.com/frappe/press/commit/7ee18730259e773ee0dcd1f3f47bed33f622dfd5
