### ISSUE TITLE
Site backup flaky test

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/press#457]
```

Traceback (most recent call last):
1054  File "/opt/python/3.10.4/lib/python3.10/unittest/mock.py", line 1369, in patched
1055    return func(*newargs, **newkeywargs)
1056  File "/home/travis/frappe-bench/apps/press/press/tests/test_cleanup.py", line 362, in test_local_backups_with_different_bench_configs_expire_sites
1057    self.assertEqual(backup_1_1.files_availability, "Available")
1058AssertionError: 'Unavailable' != 'Available'
1059- Unavailable
1060? ^^^
1061+ Available
1062? ^

```

Refer (travis run log): Traceback (most recent call last): https://app.travis-ci.com/github/frappe/press/builds/255007410

As far as I have noticed, it starts failing at around the end of a month and keeps randomly failing till the end of first week.

**Comment by NagariaHussain** [comment]
Any update on this one @balamurali27 ?

**Comment by NagariaHussain** [comment]
@shadrak98 Are you looking into this?
