### ISSUE TITLE
[Critical] Stripe Payment Failed (with traceback)

### ISSUE THREAD

**Issue by dj12djdjs** [frappe/press#459]
![image](https://user-images.githubusercontent.com/29856401/187788252-21ccf136-f05f-4a8e-b29f-72658059b61c.png)

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1503, in call
    return fn(*args, **newargs)
  File "apps/press/press/api/billing.py", line 202, in create_payment_intent_for_buying_credits
    intent = stripe.PaymentIntent.create(
  File "env/lib/python3.8/site-packages/stripe/api_resources/abstract/createable_api_resource.py", line 22, in create
    response, api_key = requestor.request("post", url, params, headers)
  File "env/lib/python3.8/site-packages/stripe/api_requestor.py", line 122, in request
    resp = self.interpret_response(rbody, rcode, rheaders)
  File "env/lib/python3.8/site-packages/stripe/api_requestor.py", line 373, in interpret_response
    self.handle_error_response(rbody, rcode, resp.data, rheaders)
  File "env/lib/python3.8/site-packages/stripe/api_requestor.py", line 152, in handle_error_response
    raise err
stripe.error.InvalidRequestError: Request req_RBcy4LHk9dAHtm: Invalid integer: 4707.0
```

**Comment by NagariaHussain** [comment]
Hi!

Is this locally running FC or in production (frappecloud.com)?

**Comment by dj12djdjs** [comment]
@NagariaHussain https://frappecloud.com/

**Comment by rutwikhdev** [comment]
Able to replicate locally. Fixes https://github.com/frappe/press/commit/1faa1f4ac66b8d186e7585e58d00d8751f788326
