### ISSUE TITLE
Clean up after archive throws

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/press#502]
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1503, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/handler.py", line 278, in run_doc_method
    response = doc.run_method(method)
  File "apps/frappe/frappe/model/document.py", line 912, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1251, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1233, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 909, in fn
    return method_object(*args, **kwargs)
  File "apps/press/press/press/doctype/site/site.py", line 570, in cleanup_after_archive
    site_cleanup_after_archive(self.name)
  File "apps/press/press/press/doctype/site/site.py", line 1173, in site_cleanup_after_archive
    delete_site_domains(site)
  File "apps/press/press/press/doctype/site/site.py", line 1180, in delete_site_domains
    frappe.delete_doc("Site Domain", domain.name)
  File "apps/frappe/frappe/__init__.py", line 1168, in delete_doc
    frappe.model.delete_doc.delete_doc(
  File "apps/frappe/frappe/model/delete_doc.py", line 121, in delete_doc
    doc.run_method("on_trash")
  File "apps/frappe/frappe/model/document.py", line 912, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1251, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1233, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 909, in fn
    return method_object(*args, **kwargs)
  File "apps/press/press/press/doctype/site_domain/site_domain.py", line 107, in on_trash
    self.remove_domain_from_site_config()
  File "apps/press/press/press/doctype/site_domain/site_domain.py", line 124, in remove_domain_from_site_config
    site_doc.remove_domain_from_config(self.domain)
  File "apps/press/press/press/doctype/site/site.py", line 446, in remove_domain_from_config
    domains.remove(domain)
ValueError: list.remove(x): x not in list

### Response Data
```
{
	"exception": "ValueError: list.remove(x): x not in list"
}
````

**Comment by NagariaHussain** [comment]
So, it just throws when the site status is not = 'Archived', when I set the status to 'Archived' and then tried cleanup, it worked as expected.
