### ISSUE TITLE
After site migration from V13 to V4 Error Code: 417, Encryption key is invalid! Please check site_config.json

### ISSUE THREAD

**Issue by michalls01** [frappe/press#536]
After site migration on FC from V13 to V14 this error occurs on the login page. Both keys in site_config.json seems to be the same.

The migration process is exactly as this Migrate using site URL - https://frappecloud.com/docs/sites/migrate-an-existing-site#migrate-using-site-url

![image](https://user-images.githubusercontent.com/79514229/194558723-bc1b2514-098c-4103-b2a0-84f10a456851.png)

Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/cryptography/fernet.py", line 127, in _verify_signature
    h.verify(data[-32:])
  File "env/lib/python3.10/site-packages/cryptography/hazmat/primitives/hmac.py", line 72, in verify
    ctx.verify(signature)
  File "env/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 85, in verify
    raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/password.py", line 216, in decrypt
    return cstr(cipher_suite.decrypt(encode(txt)))
  File "env/lib/python3.10/site-packages/cryptography/fernet.py", line 88, in decrypt
    return self._decrypt_data(data, timestamp, time_info)
  File "env/lib/python3.10/site-packages/cryptography/fernet.py", line 145, in _decrypt_data
    self._verify_signature(data)
  File "env/lib/python3.10/site-packages/cryptography/fernet.py", line 129, in _verify_signature
    raise InvalidToken
cryptography.fernet.InvalidToken

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 18, in get_response
    response = renderer_instance.render()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 78, in render
    html = self.get_html()
  File "apps/frappe/frappe/website/utils.py", line 510, in cache_html_decorator
    html = func(*args, **kwargs)
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 89, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 157, in update_context
    data = self.run_pymodule_method("get_context")
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 219, in run_pymodule_method
    return method(self.context)
  File "apps/frappe/frappe/www/login.py", line 70, in get_context
    client_secret = get_decrypted_password("Social Login Key", provider.name, "client_secret")
  File "apps/frappe/frappe/utils/password.py", line 62, in get_decrypted_password
    return decrypt(result[0][0])
  File "apps/frappe/frappe/utils/password.py", line 219, in decrypt
    frappe.throw(_("Encryption key is invalid! Please check site_config.json"))
  File "apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Encryption key is invalid! Please check site_config.json

**Comment by ankush** [comment]
looks like the encryption key from old site config wasn't get copied to new site.

**Comment by michalls01** [comment]
I tried the same process again yesterday and it works as expected. When I tried the same thing several times a few days ago, it threw the aforementioned error. Shall I close the issue?

**Comment by michalls01** [comment]
Another try with backup and restore to V14 and in a few hours after installation and testing the site - the same error appeared again.

**Comment by michalls01** [comment]
@ankush It seems this problem is resolved when manually copying the key from the old site config to the new site config (although they seem to be the same).
