### ISSUE TITLE
Encryption key is invalid. Please check site_config.json

### ISSUE THREAD

**Issue by deepakc21** [frappe/press#544]
## Description of the issue
While creating purchase invoice, I got this error - " Encryption key is invalid! Please check site_config.json ". The encryption key was missing the site_config.json section.
I have re-entered the password in the fields as suggested in the docs(https://frappecloud.com/docs/sites/migrate-an-existing-site#encryption-key)
The encryption key is now visible in the site config section in the dashboard. Also, I can now create purchase invoice successfully but the error still pops 
when I submit the pruchase invoice.

## Context information (for bug reports)

Frappe Framework - v14.10.0 - frappe/frappe:version-14
ERPNext - v14.2.3 - frappe/erpnext:version-14

## Steps to reproduce the issue

1. Create Purchase Invoice.
2. Submit the Invoice.

### Observed result
Purchase Invoice submitted successfully with a popup error - Encryption key is invalid! Please check site_config.json
![13](https://user-images.githubusercontent.com/97949896/196101664-6feaf701-5d89-4114-b7c0-90b2cdd2c91a.jpg)

### Expected result
Purchase Invoice submission without any popup error.

### Stacktrace / full error message
Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/cryptography/fernet.py", line 127, in _verify_signature
    h.verify(data[-32:])
  File "env/lib/python3.10/site-packages/cryptography/hazmat/primitives/hmac.py", line 72, in verify
    ctx.verify(signature)
  File "env/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 85, in verify
    raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/password.py", line 216, in decrypt
    return cstr(cipher_suite.decrypt(encode(txt)))
  File "env/lib/python3.10/site-packages/cryptography/fernet.py", line 88, in decrypt
    return self._decrypt_data(data, timestamp, time_info)
  File "env/lib/python3.10/site-packages/cryptography/fernet.py", line 145, in _decrypt_data
    self._verify_signature(data)
  File "env/lib/python3.10/site-packages/cryptography/fernet.py", line 129, in _verify_signature
    raise InvalidToken
cryptography.fernet.InvalidToken

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/twilio_integration/twilio_integration/overrides/notification.py", line 26, in send
    self.send_whatsapp_msg(doc, context)
  File "apps/twilio_integration/twilio_integration/overrides/notification.py", line 33, in send_whatsapp_msg
    WhatsAppMessage.send_whatsapp_message(
  File "apps/twilio_integration/twilio_integration/twilio_integration/doctype/whatsapp_message/whatsapp_message.py", line 51, in send_whatsapp_message
    message.send()
  File "apps/twilio_integration/twilio_integration/twilio_integration/doctype/whatsapp_message/whatsapp_message.py", line 14, in send
    client = Twilio.get_twilio_client()
  File "apps/twilio_integration/twilio_integration/twilio_integration/twilio_handler.py", line 114, in get_twilio_client
    auth_token = get_decrypted_password("Twilio Settings", "Twilio Settings", 'auth_token')
  File "apps/frappe/frappe/utils/password.py", line 62, in get_decrypted_password
    return decrypt(result[0][0])
  File "apps/frappe/frappe/utils/password.py", line 219, in decrypt
    frappe.throw(_("Encryption key is invalid! Please check site_config.json"))
  File "apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Encryption key is invalid! Please check site_config.json

## Additional information

OS version / distribution, `Frappe` install method, etc.

Site hosted on Frappe cloud.
Frappe Framework - v14.10.0 - frappe/frappe:version-14
ERPNext - v14.2.3 - frappe/erpnext:version-14

**Comment by ankush** [comment]
duplicate https://github.com/frappe/press/issues/543
