### ISSUE TITLE
Bug: [vite:css] Failed to find 'frappe-charts/dist/frappe-charts.min.css'

### ISSUE THREAD

**Issue by TGTGamer** [frappe/press#752]
Hi when I'm installing press on my local server following the guide, I get the following error: 

```cmd
frappe@vps-6521e2:~/frappe-bench$ bench get-app press --branch master https://github.com/frappe/press
Getting press
$ git clone https://github.com/frappe/press --branch master --depth 1 --origin upstream
Cloning into 'press'...
remote: Enumerating objects: 2018, done.
remote: Counting objects: 100% (2018/2018), done.
remote: Compressing objects: 100% (1624/1624), done.
remote: Total 2018 (delta 520), reused 1079 (delta 235), pack-reused 0
Receiving objects: 100% (2018/2018), 15.06 MiB | 14.40 MiB/s, done.
Resolving deltas: 100% (520/520), done.
Ignoring dependencies of https://github.com/frappe/press. To install dependencies use --resolve-deps
Installing press
$ /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/frappe/frappe-bench/apps/press
$ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

$ cd dashboard && yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "frappe-ui > @tiptap/extension-color@2.0.0-beta.220" has unmet peer dependency "@tiptap/core@^2.0.0-beta.209".
warning "frappe-ui > @tiptap/extension-highlight@2.0.0-beta.220" has unmet peer dependency "@tiptap/core@^2.0.0-beta.209".
warning "frappe-ui > @tiptap/extension-image@2.0.0-beta.220" has unmet peer dependency "@tiptap/core@^2.0.0-beta.209".
warning "frappe-ui > @tiptap/extension-link@2.0.0-beta.220" has unmet peer dependency "@tiptap/core@^2.0.0-beta.209".
warning "frappe-ui > @tiptap/extension-mention@2.0.0-beta.220" has unmet peer dependency "@tiptap/core@^2.0.0-beta.209".
warning "frappe-ui > @tiptap/extension-placeholder@2.0.0-beta.220" has unmet peer dependency "@tiptap/core@^2.0.0-beta.209".
warning "frappe-ui > @tiptap/extension-table@2.0.0-beta.220" has unmet peer dependency "@tiptap/core@^2.0.0-beta.209".
warning "frappe-ui > @tiptap/extension-table-cell@2.0.0-beta.220" has unmet peer dependency "@tiptap/core@^2.0.0-beta.209".
warning "frappe-ui > @tiptap/extension-table-header@2.0.0-beta.220" has unmet peer dependency "@tiptap/core@^2.0.0-beta.209".
warning "frappe-ui > @tiptap/extension-table-row@2.0.0-beta.220" has unmet peer dependency "@tiptap/core@^2.0.0-beta.209".
warning "frappe-ui > @tiptap/extension-text-align@2.0.0-beta.220" has unmet peer dependency "@tiptap/core@^2.0.0-beta.209".
warning "frappe-ui > @tiptap/extension-text-style@2.0.0-beta.220" has unmet peer dependency "@tiptap/core@^2.0.0-beta.209".
warning "frappe-ui > @tiptap/extension-typography@2.0.0-beta.220" has unmet peer dependency "@tiptap/core@^2.0.0-beta.209".
warning "frappe-ui > @tiptap/pm@2.0.0-beta.220" has unmet peer dependency "@tiptap/core@^2.0.0-beta.209".
warning "frappe-ui > @tiptap/prosemirror-tables@1.1.4" has unmet peer dependency "prosemirror-keymap@^1.1.2".
warning "frappe-ui > @tiptap/prosemirror-tables@1.1.4" has unmet peer dependency "prosemirror-model@^1.8.1".
warning "frappe-ui > @tiptap/prosemirror-tables@1.1.4" has unmet peer dependency "prosemirror-state@^1.3.1".
warning "frappe-ui > @tiptap/prosemirror-tables@1.1.4" has unmet peer dependency "prosemirror-transform@^1.2.1".
warning "frappe-ui > @tiptap/prosemirror-tables@1.1.4" has unmet peer dependency "prosemirror-view@^1.13.3".
warning "frappe-ui > @tiptap/suggestion@2.0.0-beta.220" has unmet peer dependency "@tiptap/core@^2.0.0-beta.209".
warning "frappe-ui > @tiptap/vue-3@2.0.0-beta.220" has unmet peer dependency "@tiptap/core@^2.0.0-beta.209".
warning "frappe-ui > @tiptap/vue-3 > @tiptap/extension-bubble-menu@2.0.0-beta.220" has unmet peer dependency "@tiptap/core@^2.0.0-beta.209".
warning "frappe-ui > @tiptap/vue-3 > @tiptap/extension-floating-menu@2.0.0-beta.220" has unmet peer dependency "@tiptap/core@^2.0.0-beta.209".
warning " > @vue/test-utils@2.3.1" has unmet peer dependency "@vue/compiler-dom@^3.0.1".
warning " > @vue/test-utils@2.3.1" has unmet peer dependency "@vue/server-renderer@^3.0.1".
[4/4] Building fresh packages...
Done in 13.97s.
Done in 17.38s.
$ bench build --app press
✔ Application Assets Linked


yarn run v1.22.19
$ node esbuild --production --apps press --run-build-command
clean: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
File                                                        Size

press/dist/js/
└─ marketplace.bundle.AGE5ESMU.js                           17.58 Kb

 DONE  Total Build Time: 13.152s

clean: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration

Running build command for press
$ NODE_ENV=production yarn run build-all
$ yarn run build-app && yarn run build-email-css && yarn run build-marketplace-css && yarn run build-saas-css
$ cd dashboard && yarn build
$ yarn generate-theme-config && vite build --base=/assets/press/dashboard/ && yarn copy-html-entry
$ node ./generateThemeConfig.js
vite v2.9.15 building for production...
✓ 520 modules transformed.
[vite:css] Failed to find 'frappe-charts/dist/frappe-charts.min.css'
  in [
    /home/frappe/frappe-bench/apps/press/dashboard/src/assets
  ]
file: /home/frappe/frappe-bench/apps/press/dashboard/src/assets/style.css?vue&type=style&index=0&src=409962a6&lang.css
error during build:
Error: Failed to find 'frappe-charts/dist/frappe-charts.min.css'
  in [
    /home/frappe/frappe-bench/apps/press/dashboard/src/assets
  ]
    at /home/frappe/frappe-bench/apps/press/dashboard/node_modules/vite/dist/node/chunks/dep-a9015192.js:82:13
    at async Promise.all (index 0)
    at async LazyResult.runAsync (/home/frappe/frappe-bench/apps/press/dashboard/node_modules/postcss/lib/lazy-result.js:396:11)
    at async compileCSS (/home/frappe/frappe-bench/apps/press/dashboard/node_modules/vite/dist/node/chunks/dep-689425f3.js:37463:27)
    at async Object.transform (/home/frappe/frappe-bench/apps/press/dashboard/node_modules/vite/dist/node/chunks/dep-689425f3.js:37010:55)
    at async transform (/home/frappe/frappe-bench/apps/press/dashboard/node_modules/rollup/dist/shared/rollup.js:22042:16)
    at async ModuleLoader.addModuleSource (/home/frappe/frappe-bench/apps/press/dashboard/node_modules/rollup/dist/shared/rollup.js:22267:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed: yarn build
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at run_build_command_for_apps (/home/frappe/frappe-bench/apps/frappe/esbuild/esbuild.js:433:5)
    at /home/frappe/frappe-bench/apps/frappe/esbuild/esbuild.js:88:35
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 27664,
  stdout: null,
  stderr: null
}
Done in 140.84s.
```

Server Details:
```
Clean production install with just bench and a new site to install press onto
Ubuntu 22.04
```

Guide followed: 
https://frappecloud.com/docs/local-fc-setup#create-your-site

**Comment by rutwikhdev** [comment]
https://github.com/frappe/press/commit/a9536a9cff8073d5b96acb4dfae6b5725483aa54 fixes
