### ISSUE TITLE
TLS ERROR: Index List Out of Range Error on Local Deployment

### ISSUE THREAD

**Issue by flexcomng** [frappe/press#854]
I am trying to deploy the Press app for local development I am getting this error after setting up the Root Login parameters:

```
Form/TLS Certificate/*.portal.mydomain.com
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1608, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/handler.py", line 304, in run_doc_method
    response = doc.run_method(method)
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/press/press/press/doctype/tls_certificate/tls_certificate.py", line 36, in obtain_certificate
    get_current_team(),
  File "apps/press/press/utils/__init__.py", line 60, in get_current_team
    team = team_dict[0].name
IndexError: list index out of range

```

The root domain is portal.mydomain.com and it is pointed to the instance hosting the press app. The Instance has a Frappe Development install and running on port 8000.

How can this be resolved?

**Comment by DevOpsFreako** [comment]
Hey @flexcomng 
If you You Got The Answer then please Share with me also 
TLS ERROR: Index List Out of Range Error on Local Deployment #854

**Comment by rutwikhdev** [comment]
@DevOpsFreako @flexcomng 

Can you check if a Team doc for Administrator user is created? This is done when you create the first user. Check error logs if something failed.

Alternatively you can run this in your sites `bench console` 
```python
team_dict = frappe.db.sql(
	"""select t.name from `tabTeam` t
	inner join `tabTeam Member` tm on tm.parent = t.name
	where tm.user = %s and tm.parenttype = 'Team' and t.enabled = 1
	order by t.creation asc
	limit 1""",
	frappe.session.user,
	as_dict=True,
)
print(team_doc)
```
If the above code returns a list like `[{"name": "Administrator"}]` that means your team is properly set. Else you might have to create a team doc manually and set user field there.
