### ISSUE TITLE
Show proper error message if existing code space exists

### ISSUE THREAD

**Issue by michellealva** [frappe/press#981]
Nothing is shown on screen on clicking on Create

<img width="1680" alt="image" src="https://github.com/frappe/press/assets/50285544/ede67f72-0ed8-46fb-9410-9235142318e3">

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 56, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 53, in handle
    return _RESTAPIHandler(call, doctype, name).get_response()
  File "apps/frappe/frappe/api.py", line 69, in get_response
    return self.handle_method()
  File "apps/frappe/frappe/api.py", line 79, in handle_method
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1586, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "apps/press/press/api/spaces.py", line 96, in create_code_server
    code_server = frappe.get_doc(
  File "apps/frappe/frappe/model/document.py", line 269, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1061, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 926, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1280, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1262, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 923, in fn
    return method_object(*args, **kwargs)
  File "apps/press/press/press/doctype/code_server/code_server.py", line 20, in validate
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 523, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 491, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 440, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Code Server mich-code.frappe.space already exists please choose a different name
```

**Comment by adityahase** [comment]
CodeSpaces have been removed
